<a href="https://colab.research.google.com/github/dpakkaushik/MachineLearning/blob/main/TF_IDF_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NOTE:

1. Please implement the TFIDf function such that for each word in a sentence, its corresponding tfidf value is assigned. Thus a 4 x 6 sized matrix should be returned where the rows represent sentences and the columns represent words. We wish to keep it simple in the beginning.

2. In reality the TFIDF function should return a matrix where the rows represent sentences and the columns represent words (ie: Features). Every sentence vector in this matrix will be 'd' dimensional, where d = number of unique words in the corpus (ie: Vocabulary).
Every position/cell in a sentence vector correponds to a particular word in the vocabulary. If the word is not present in the current sentence, we assign a value of 0 to that cell, else we assign the TFIDF value.

# **Implement TF-IDF from scratch**

In this assignment, you will implement TF-IDF vectorization of text from scratch using only Python and inbuilt data structures. You will then verify the correctness of the your implementation using a "grader" function/cell (provided by us) which will match your implmentation.

The grader fucntion would help you validate the correctness of your code. 

Please submit the final Colab notebook in the classroom ONLY after you have verified your code using the grader function/cell.

**(FAQ) Why bother about implementing a function to compute TF-IDF when it is already available in major libraries?**

Ans.
1. It helps you improve your coding proficiency.
2. It helps you obtain a deeper understanding of the concepts and how it works internally. Knowledge of the internals will also help you debug problems better.
3. A lot of product based startups and companies do focus on this in thier interviews to gauge your depth and clarity of understanding along with your programming skills. Hence, most top universities have implementations of some ML algorithms/concepts as mandatory assignments.

**NOTE: DO NOT change the "grader" functions or code snippets written by us.Please add your code in the suggested locations.**

Ethics Code:
1. You are welcome to read up online resources to implement the code. 
2. You can also discuss with your classmates on the implmentation over Slack.
3. But, the code you wirte and submit should be yours ONLY. Your code will be compared against other stduents' code and online code snippets to check for plagiarism. If your code is found to be plagiarised, you will be awarded zero-marks for all assignments, which have a 10% wieghtage in the final marks for this course.

In [ ]:
# Corpus to be used for this assignment

corpus = [
     'this is the first document mostly',
     'this document is the second document',
     'and this is the third one',
     'is this the first document here',
]

In [ ]:
# Please implement this fucntion and write your code wherever asked. Do NOT change the code snippets provided by us.
def computeTFIDF (corpus):
  """Given a list of sentences as "corpus", return the TF-IDF vectors for all the 
  sentences in the corpus as a numpy 2D matrix. 
  
  Each row of the 2D matrix must correspond to one sentence 
  and each column corresponds to a word in the text corpus. 
  
  Please order the rows in the same order as the 
  sentences in the input "corpus". 
    
  Ignore puncutation symbols like comma, fullstop, 
  exclamation, question-mark etc from the input corpus.
  
  For e.g, If the corpus contains sentences with these 
  9 distinct words, ['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this'], 
  then the first column of the 2D matrix will correpsond to word "and", the second column will 
  correspond to column "document" and so on. 
  
  Write this function using only basic Python code, inbuilt Data Structures and  NumPy ONLY.

  Implement the code as optimally as possible using the inbuilt data structures of Python.
  """

  ##############################################################
  ####   YOUR CODE BELOW  as per the above instructions #######
  ##############################################################




# Grader Cell
Please execute the following Grader cell to verify the correctness of your above implementation. This cell will print "Success" if your implmentation of the computeTFIDF() is correct, else, it will print "Failed". Make sure you get a "Success" before you submit the code in the classroom.

In [ ]:
###########################################
## GRADER CELL: Do NOT Change this.
# This cell will print "Success" if your implmentation of the computeTFIDF() is correct.
# Else, it will print "Failed"
###########################################
import numpy as np

# compute TF-IDF using the computeTFIDF() function
X_custom = computeTFIDF(corpus)

# Reference grader array - DO NOT MODIFY IT
X_grader = np.array(
    [[0, 0, 0, 0.12, 0.05, 0.23],
     [0, 0.1, 0, 0, 0.23, 0.1],
     [0.23, 0, 0, 0, 0.23, 0.23],
     [0, 0, 0, 0.12, 0.05, 0.23]]
     )

# compare X_grader and X_custom
comparison = (X_grader == X_custom)
isEqual = comparison.all()

if isEqual:
  print("******** Success ********")
else:
  print("####### Failed #######")
  print("\nX_grader = \n\n", X_grader)
  print("\n","*"*50)
  print("\nX_custom = \n\n", X_custom)


None
####### Failed #######

X_grader = 

 [[0.   0.   0.   0.12 0.05 0.23]
 [0.   0.1  0.   0.   0.23 0.1 ]
 [0.23 0.   0.   0.   0.23 0.23]
 [0.   0.   0.   0.12 0.05 0.23]]

 **************************************************

X_custom = 

 None


1. - Given two string arrays word1 and word2, return true if the two arrays represent the same string, and false otherwise.
- A string is represented by an array if the array elements concatenated in order forms the string.



In [ ]:
1. - Given two string arrays word1 and word2, return true if the two arrays represent the same string, and false otherwise.
- A string is represented by an array if the array elements concatenated in order forms the string.


In [ ]:
word1 =['abc','d','defg']
word2=['abcdde'+'fg']

s=func1(word1)
r=func1(word2)
def func(s,r):
    if(s==r):
      return True
    else:
         return False

func(s,r) 


True

In [ ]:

def func1(word1):
    string1=''
    for i in range(0,len(word1)):
        string1=string1+word1[i]
    return string1

s=func1(word1)
r=func1(word2)

2. Given a square matrix mat, return the sum of the matrix diagonals.
- Only include the sum of all the elements on the primary diagonal and all the elements on the secondary diagonal that are not part of the primary diagonal.
123
456
789


In [ ]:
output : [1,5,9,3,7]


In [ ]:
# import numpy as np
# a=np.matrix[1]
a=[[1,2,3],[4,5,6],[7,8,9]]
print(a)
a=[1,2,3,4,5,6,7,8,9]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:

def func3(a):
    list1=[]
    for i in range(0,len(a)):
        for j in range(0,len(a)):
          if(i==j & a[i] not in list1):

             list1.append(a[i])
    return list1
       
s=func3(a)
print(s)
# v=[]
# for i in range(0,len(s)):
#     if(s[i] not in s):
#        v.append(s[i])
# print(v)

[1, 1, 1, 1, 1, 3, 3, 5, 5, 7, 9]


In [ ]:
a='this  is a string'

list2=[]
list2= a.split(" ")
list2  

['this', '', 'is', 'a', 'string']

In [ ]:
for word in list2:
    word

In [ ]:
a='this'

list2=[]
list2= a.split("")
list2

['this']